version: '3.8'

services:
  # Backend API Container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: athar-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
      - JWT_EXPIRE=7d
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD='Alihadi0773788%'
      - DB_NAME=athar_db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - athar-network
    restart: always

  # Dashboard Frontend Container
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000/api
    container_name: athar-dashboard
    ports:
      - "3001:3001"
    restart: always

  # MySQL Database Container
  db:
    image: mariadb:10.6
    container_name: athar-db
    command: --lower_case_table_names=1
    ports:
      - "3307:3306" # يمكنك الوصول للقاعدة من السيرفر عبر 3307
    environment:
      # لاحظ هنا قمنا بتغيير اسم المتغيرات لتناسب MariaDB
      MARIADB_ROOT_PASSWORD: 'Alihadi0773788%'
      MARIADB_DATABASE: athar_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - athar-network
    restart: always
networks:
  athar-network:
    driver: bridge

volumes:
  db_data:
